sudo: required
services:
  - docker

before_install:
  - docker build -t andresguevaracaprio/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andresguevaracaprio/docker-react npm run test
