sudo: required
services:
  - docker

before_install:
  - docker build -t andresguevaracaprio/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andresguevaracaprio/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-193831038647"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY_ID
secret_key_id:
  secure: "$AWS_SECRET_ACCESS_KEY"
